#include<cstdio>
#include<iostream>
#include<bits/stdc++.h>

using namespace std;
char a[105][105];
int b[105][105];
int x2[8] = {0, 1, 1, 1, 0, -1, -1, -1};
int y2[8] = {1, 1, 0, -1, -1, -1, 0, 1};

int main() {
    string s = "12345";
    cout << s.size()<<endl;
    return 0;
}
TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT